# Generated by Django 5.0.4 on 2024-05-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TennisPlayer',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('hand', models.IntegerField()),
                ('height', models.IntegerField()),
                ('country', models.TextField()),
                ('age', models.IntegerField()),
                ('total_w_aces', models.IntegerField(default=0)),
                ('total_w_df', models.IntegerField(default=0)),
                ('total_l_aces', models.IntegerField(default=0)),
                ('total_l_df', models.IntegerField(default=0)),
                ('rank', models.IntegerField()),
                ('rank_points', models.IntegerField()),
                ('num_of_wins', models.IntegerField(default=0)),
                ('num_of_loss', models.IntegerField(default=0)),
                ('no_of_matches', models.IntegerField(default=0)),
                ('total_minutes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.TextField()),
                ('surface', models.TextField()),
                ('score', models.TextField()),
                ('minutes', models.IntegerField()),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_matches', to='tennis_oracle.tennisplayer')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='tennis_oracle.tennisplayer')),
            ],
        ),
    ]
