# Generated by Django 5.0.4 on 2024-05-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_oracle', '0001_changed_my_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennisplayer',
            name='height',
            field=models.IntegerField(null=True),
        ),
    ]
